### ISSUE TITLE
Đề xuất mô hình

### ISSUE THREAD

**Issue by trnamanh12** [baitaploncnpm66/Major-Assignment-INT2208-5#11]
Phân mềm sẽ giúp nguời có thêm nhiều góc nhìn từ các nguời dùng đã mua sản phẩm rồi bằng cách:
Với mỗi sản phẩm có thể trên các trang web bán hàng lớn liên quan đến công nghệ như Thế giới di động,,,,
Nguời dùng sẽ nhập tên sản phẩm đó vào phần mềm
Phần mềm sẽ dựa trên dữ liệu thu nhập từ các review của nguời khác sau đó sẽ dự đoán các aspect ví dụ như: Price, Pin, Màn hình, Performance đuợc nguời dùng khác đánh giá kém hay tốt, sản phẩm đó thuờng đưọc nhiều nguời dùng chê hay khen và chê hay khen về vấn đề nào, sau đó nguời dùng có thể đưa ra quyết định mua hay không

**Comment by buma04** [comment]
Issue gốc ở [đây](https://github.com/manhbd-22022602/Major-Assignment-INT2208-5/issues/10)
