### ISSUE TITLE
Tìm hiểu về tính khả thi của việc thiết kế web trên sites.google.com

### ISSUE THREAD

**Issue by buma04** [baitaploncnpm66/Major-Assignment-INT2208-5#12]
Xem xét có thể thiết kế hệ thống trên sites.google.com được hay không. Nếu không phải tự tìm hiểu và thiết kế web từ các python framework

**Comment by NinhDT22022522** [comment]
Nếu chưa ai nhận phần việc này thì tôi muốn thử, hạn là 11h59p ngày 17/4 sẽ báo cáo lại cho cả nhóm

**Comment by NinhDT22022522** [comment]
Báo cáo: việc thiết kế bằng Google site khả thi nhưng có vẻ không phù hợp với mục tiêu của môn học vì GG site không có khả năng mở rộng cao, không có nhiều khả năng tùy biến, phát triển lâu dài
