### ISSUE TITLE
Chọn chủ đề và đặt tên cho dự án

### ISSUE THREAD

**Issue by buma04** [baitaploncnpm66/Major-Assignment-INT2208-5#5]
Mọi người comment bên dưới gợi ý chủ đề và tên cho dự án

**Comment by NinhDT22022522** [comment]
Duolingo thì sao các bạn

**Comment by buma04** [comment]
Chọn topic nữa

**Comment by HungLV2512** [comment]
làm về tính năng note từ vựng trong duolingo đc k nhỉ

**Comment by NinhDT22022522** [comment]
cái bạn nghĩ sao về việc từ thuật toán trò n-puzzle, chúng ta phát triển thêm giao diện và tính năng cho trò chơi
