### ISSUE TITLE
Chốt chủ đề dự án

### ISSUE THREAD

**Issue by buma04** [baitaploncnpm66/Major-Assignment-INT2208-5#6]
Nhóm chúng ta sẽ làm trang web phân tích bán hàng.
Dự án này sẽ được kế thừa từ dự án Mobile e-commerce review analysis (https://github.com/NinhDT22022522/Mobile-e-commerce-review-sentiment-classification). Tạm thời từ giờ đến 1/4 sẽ tập trung hoàn thành dự án kia nên mọi tiến độ hay issue sẽ được cập nhật ở đường link phía trên

**Comment by NinhDT22022522** [comment]
chắc là ổn :'))

**Comment by NinhDT22022522** [comment]
Hình như có thể merge hai repo lại thành 1

**Comment by NinhDT22022522** [comment]
hoặc là mình có thể đổi dự án này bằng link của dự án https://github.com/NinhDT22022522/Mobile-e-commerce-review-sentiment-classification và tiếp tục phát triển :v
